### ISSUE TITLE
generate test data bundle on build

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-csw202#11]
The test data in https://github.com/opengeospatial/ets-csw202/tree/master/src/site/resources (which is a `.zip` of https://github.com/opengeospatial/ets-csw202/tree/master/src/main/resources/data) should be generated on build/release instead of housed in version control.

This would ensure consistency between the actual test data and their bundle, as well as reduce the need to manage this manually in two areas.

**Comment by lorebiga** [comment]
@tomkralidis I've progressed on this a bit. Now the data are created at build time, but I'm not sure they get included in the site bundle. Your comments are welcome.

**Comment by kalxas** [comment]
Thank you @lorebiga 
Any timeline for these changes to be deployed on beta CITE?

**Comment by tomkralidis** [comment]
Thanks @lorebiga.  I've issued https://github.com/opengeospatial/ets-csw202/pull/13 with a minor fix.  Great work!

**Comment by bermud** [comment]
@kalxas, we are trying to standardized the time we release tests at TEAM Engine beta. We often do it once per month. The next release will be by the end of July. More details [here](https://github.com/opengeospatial/cite/wiki/Releasing-Tests-to-the-OGC-Testing-Infrastructure).

**Comment by kalxas** [comment]
thanks @bermud

**Comment by lorebiga** [comment]
thank you @tomkralidis, I've added your name to the contributors list :+1: 

PS: I think the data file (csw-2.0.2-data.zip) should have the standard assembly name (e.g. ets-csw20-1.13-SNAPSHOT-data.zip), as it would include the correct build version. However, this would need filtering a few files, POM hacking, etc., so I'd leave it as it is, for the time being.
