### ISSUE TITLE
run tests with properties file as argument

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-csw202#14]
In the context of running via console/command line, the file `src/test/resources/sut.properties` needs to be updated to test a different CSW.

Similar to [ets-cat30](https://github.com/opengeospatial/ets-cat30), update `mvn test` to accept this file (or some config file like https://github.com/opengeospatial/ets-cat30/blob/master/src/main/resources/test-run-props.xml) as an argument (with the fallback behaviour being to use `src/test/resources/sut.properties`.

This will allow the user to manage their own config without modifying files under version control.

**Comment by bermud** [comment]
This test is written in CTL, so we can create an xml that passes the values of the instance that needs to be tested. It is explained here: http://opengeospatial.github.io/teamengine/users.html, section 'Running with no User Interaction'

**Comment by lorebiga** [comment]
Thanks for answering this question, Luis.

I checked into CSW 3.0, but I haven’t found what’s the strategy there to implement what Tom suggested.
Perhaps a maven property would do.

If Tom replies, we can sort that out differently,
  L


> Il giorno 07 gen 2016, alle ore 19:07, Luis Bermudez <notifications@github.com> ha scritto:
> 
> Closed #14 <https://github.com/opengeospatial/ets-csw202/issues/14>.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/opengeospatial/ets-csw202/issues/14#event-508548254>.
> 

---
Lorenzo Bigagli, Ph.D.
National Research Council of Italy
Institute of Atmospheric Pollution Research (CNR-IIA)
Earth and Space Science Informatics Laboratory (ESSI-Lab)

a: Area della Ricerca di Firenze
   Via Madonna del Piano 10
   50019 Sesto Fiorentino (FI), Italia
t: +39 055 5226582
m: lorenzo.bigagli@cnr.it
m: l.bigagli@iia.cnr.it

**Comment by tomkralidis** [comment]
cc @rjmartell 

I'm not exactly sure how the csw30 tests do this, but the user instructions at https://github.com/opengeospatial/ets-cat30#2-integrated-development-environment-ide would be a good model to follow.
