### ISSUE TITLE
skip testing from build

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-csw202#15]
Running `mvn install` will run tests against the CSW configured in `src/test/resources/sut.properties`.

I'm not family with Maven semantics, but is there any way to build the software without running the tests?

- tests run against remote resources, which will break if not connected to the Internet
- if the user has modified `src/test/resources/sut.properties` with a local CSW which is turned off the build attempt returns errors

**Comment by bermud** [comment]
To skip the tests run mvn -Dmaven.test.skip=true install

**Comment by tomkralidis** [comment]
Perfect, thanks @bermud!
