### ISSUE TITLE
CITE CSW 202 not parsing extended capablities

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-csw202#2]
It seems that the tests for CSW202 have troubles parsing the following CSW
2.0.2 capabilities document, which are valid, according to Altova XMLSpy 2013
and Stylus Studio 2011:

http://inspire-geoportal.ec.europa.eu/GeoportalProxyWebServices/resources/OGC
CSW202?service=CSW&version=2.0.2&request=GetCapabilities

I believe this is the cause why in the attached logs it sasys that the reponse
body is empty, which is not.

**Log for test s0003/d1e6546_1/d1e6408_1/d1e383_1**
Test csw:csw-2.0.2-GetCapabilities-tc1.1 (s0003/d1e6546_1/d1e6408_1/d1e383_1)
Assertion:
      All OGC web services must implement GetCapabilities using the GET method.
      The response to a GetCapabilities request without the optional version
      parameter must include a complete representation of the capabilities
      document corresponding to the latest supported version.   

Request d1e466_1:
   Method: GET
   URL: [http://inspire-geoportal.ec.europa.eu/GeoportalProxyWebServices/resou
rces/OGCCSW202?service=CSW&request=GetCapabilities]()

Response from parser p:XMLValidatingParser.CSW:
** Messages from parser p:XMLValidatingParser.CSW:**

Validation error:
cvc-elt.4.2: Cannot resolve 'inspire_common:citationInspireInteroperabilityRegulation_eng' to a type definition for element 'inspire_common:Specification'.

Validation error:
  cvc-elt.4.2: Cannot resolve 'inspire_common:classificationOfSpatialDataService' to a type definition for element 'inspire_common:MandatoryKeyword'.

Validation error:
  cvc-elt.4.2: Cannot resolve 'inspire_common:inspireTheme_eng' to a type
definition for element 'inspire_common:Keyword'.

3 validation errors detected.

Message d1e490_1:
FAILURE: Missing response entity.
Result: Failed

I have attached the log files downloaded via your form.

Link: http://inspire-geoportal.ec.europa.eu/GeoportalProxyWebServices/resources/OGCCSW202?service=CSW&version=2.0.2&request=GetCapabilities

[Originally reported in the OGC CITE issue tracker: issue #864](https://portal.opengeospatial.org/?m=projects&a=view&project_id=85&tab=5&act=details&issue_id=864)  

Entered by: Quaglia, Angelo

_Opened: 2013-09-05 07:58:48 Last Updated: 2013-11-18 12:39:07_

**Comment by lorebiga** [comment]
Release note: the test requires that the capabilities document contains all the schema locations necessary for validation.
