### ISSUE TITLE
Update CTL with better information about conformance classes 

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/ets-csw202#20]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:
https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by lorebiga** [comment]
thanks for reporting, should be ok now. I'm testing it, feel free to double check.
