### ISSUE TITLE
Test csw:csw-2.0.2-GetCapabilities-tc1.3 fails 

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-csw202#24]
## Setup
SUT: TODO
Tested with [production ](http://cite.opengeospatial.org/teamengine/)
 * ETS CSW 1.16 
 * TEAM Engine 4.10

and local docker environment
 * ETS CSW 1.18-SNAPSHOT
 * TEAM Engine 5.2

## Testfailure
Validating the response
```
<ExceptionReport xmlns="http://www.opengis.net/ows" version="1.2.0">
  <Exception exceptionCode="VersionNegotiationFailed" locator="acceptVersions">
    <ExceptionText>
      [Version negotiation failed, acceptVersions]: locator={1}
    </ExceptionText>
    <ExceptionText>
      None of the supplied parameter values are supported.
    </ExceptionText>
  </Exception>
  <!--Response received in [84] milliseconds-->
</ExceptionReport>
```
fails with:
 * Error 1: cvc-elt.1.a: Cannot find the declaration of element 'ExceptionReport'.

The [reference implementation](http://demo.pycsw.org/cite/csw?service=CSW&acceptVersions=2.0.2&request=GetCapabilities) passes the test, the response is an OWS 2.0.0  ExceptionReport.

**Comment by lgoltz** [comment]
[OGC CSW 2.0.2 Specification](http://portal.opengeospatial.org/files/?artifact_id=20555)

```
10.3.7 Exception reporting

In the event that a catalogue service encounters an error while processing a request or
receives an unrecognised request, it shall generate an XML document indicating that an
error has occurred. The format of the XML error response is specified by, and shall
validate against, the exception response schema defined in clause 8 of the OWS Common
Implementation Specification [OGC 05-008c1].

An <ows:ExceptionReport> element may contain one or more catalogue processing
exceptions specified using the <ows:Exception> element. The mandatory version
attribute is used to indicate the version of the service exception report schema. For this
version of the specification, this value is fixed at 1.2.0. The optional language attribute
may be used to indicate the language used. The code list for the language parameter is
defined in IETF RFC 1766.
```

As far as see the response with OWS ExceptionReport version 1.2.0 is fine and the test has to fixed (as well as the reference implementation) .

@lorebiga What do you think about this?

**Comment by lorebiga** [comment]
Hi @lgoltz , sorry for the belated reply... What's the issue here? It looks like a validation error... Is SchemaLocation right?

**Comment by lgoltz** [comment]
@lorebiga No problem, thanks! Yes, it is a validation error. There is no schemaLocation in the response.

**Comment by lorebiga** [comment]
if I remember well, the schema location should be indicated to the validatingParser instance, with an appropriate initialization parameter. I think this issue and similar others may be closed.

**Comment by dstenger** [comment]
@keshav-nangare Can you please check if this issue can be closed?

**Comment by keshav-nangare** [comment]
@dstenger 

As mentioned in an earlier comment by Lyn, there is no schema location in service so tests are getting failed. I have verified with other services [1] and [2] test suite gets executed successfully.

[1] http://demo.pycsw.org/cite/csw?service=CSW&acceptVersions=2.0.2&request=GetCapabilities
[2] http://ri.essi-lab.eu/gi-cat-RI/services/cswiso?service=CSW&version=2.0.2&request=GetCapabilities

I think we can close this issue.
