### ISSUE TITLE
New HTML report does not list tests 

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-csw202#27]
Furthermore a WMS is referenced as Capabilities URL.

Can be tested in [beta](http://cite.opengeospatial.org/te2/) with http://demo.pycsw.org/cite/csw?service=CSW&acceptVersions=2.0.2&request=GetCapabilities

**Comment by dstenger** [comment]
# Functional test

Tested with [teamengine-docker](https://github.com/opengeospatial/teamengine-docker) and [1].

Now, all tests are listed and report is shown correctly.

[1] http://demo.pycsw.org/cite/csw?service=CSW&acceptVersions=2.0.2&request=GetCapabilities
