### ISSUE TITLE
Test csw:csw-2.0.2-GetCapabilities-tc7.2  requires FilterCapabilities even though that section has not been requested

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-csw202#4]
Result:
      
    Test csw:csw-2.0.2-GetCapabilities-tc7.2 type Mandatory default result Passed (s0004/d1433e6483_1/d1433e6345_1/d1433e435_1)
    
    Assertion: 
          The response to a GetCapabilities request that includes a sections parameter 
          listing optional elements shall include only the requested elements in the 
          response entity.
          
    
    Request d1433e1136_1:
       Method: GET
       URL: http://inspire-geoportal.ec.europa.eu/GeoportalProxyWebServices/resources/OGCCSW202?service=CSW&request=GetCapabilities&sections=OperationsMetadata,ServiceIdentification
       Response from parser p:XMLValidatingParser.CSW:
          
       Messages from parser p:XMLValidatingParser.CSW:
            Validation error:
      cvc-complex-type.2.4.b: The content of element \'ns4:Capabilities\' is not complete. One of \'{\""http://www.opengis.net/ogc\"":Filter_Capabilities}\' is expected.
    1 validation error detected.
    
    
    Message d1433e1164_1:
       FAILURE: Missing response entity.
    
    Result: Failed

[Originally reported in the OGC CITE issue tracker: issue #922](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=922)  

Entered by: Quaglia, Angelo

_Opened: 2013-12-16 11:33:43 Last Updated: 2014-01-07 05:34:10_

**Comment by bermud** [comment]
@lorebiga, do we have any final resolution to this question/issue?

**Comment by lorebiga** [comment]
Filter_Capabilities is mandatory in the response, as per the Capabilities schema. The test fails because the response is invalid without that.

The test comment reads: "Pass if the response is schema valid and includes only the requested optional elements."

From OGC 05-008: 7.3.3 (p.17) and OGC 07-006r1: 7.2.3.2 (p.30-31), the response to a GetCapabilities request that includes a sections parameter listing optional elements shall be a valid document including only the requested optional elements.

**Comment by lorebiga** [comment]
Hi dear Luis!

I hope your holiday went well and 2016 is great!

I’ve checked and closed the issue. I had planned of closing all at the end of November, I apologise for the delay (had a chapter to write that took me longer, plus Xmas, etc.)

Now, also thanks to your contribution, we are ready to roll 1.15 to beta. Let me know if I should wait a little more towards the end of the month (in case some other issues pop up), or I can do it now.

All the best, dear, hope to see you soon!
  Lorenzo


> Il giorno 07 gen 2016, alle ore 19:08, Luis Bermudez <notifications@github.com> ha scritto:
> 
> @lorebiga <https://github.com/lorebiga>, do we have any final resolution to this question/issue?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/opengeospatial/ets-csw202/issues/4#issuecomment-169759358>.
> 

---
Lorenzo Bigagli, Ph.D.
National Research Council of Italy
Institute of Atmospheric Pollution Research (CNR-IIA)
Earth and Space Science Informatics Laboratory (ESSI-Lab)

a: Area della Ricerca di Firenze
   Via Madonna del Piano 10
   50019 Sesto Fiorentino (FI), Italia
t: +39 055 5226582
m: lorenzo.bigagli@cnr.it
m: l.bigagli@iia.cnr.it

**Comment by bermud** [comment]
Fixed with 862d4857ecf6bc04f435fce0f608fa3ca30a933b
