### ISSUE TITLE
allow for higher versions than CSW 2.0.2

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-csw202#8]
CSW 2.0.2 (using OWS Common 1.0.0) and CSW 3.0.0 (using OWS Common 2.0.0) both prescribe (in clause 7.3.2):

> Furthermore, if a server receives a GetCapabilities request without the AcceptVersions parameter, it shall return a service metadata document that is compliant to the highest protocol version that the server supports

Now that CSW 3.0.0 is available, a given endpoint supporting both CSW 2.0.2 and CSW 3.0.0 returns 3.0.0 per clause 7.3.2.

The CSW 2.0.2 tests need to account for newer response on some of the tests so they do not fail if a higher (albiet not 2.0.2) version is returned.

**Comment by kalxas** [comment]
+1

**Comment by lorebiga** [comment]
hi Tom, I think test 'csw:csw-2.0.2-GetCapabilities-tc1.1' should be amended to force 2.0.2 Capabilities to be returned, by adding the 'AcceptVersions' parameter.
Would it work for you?

**Comment by tomkralidis** [comment]
Hi @lorebiga, agree.  Either `acceptversions=2.0.2` or `version=2.0.2` (latter is preferable).

**Comment by lorebiga** [comment]
for what I see from the specs, AcceptVersions should be the one...

**Comment by lorebiga** [comment]
I've added the AcceptVersions parameter, let me know if the fix works.

**Comment by tomkralidis** [comment]
Works when testing locally.  Thanks!

**Comment by lorebiga** [comment]
Great! Thanks for reporting!
